### PR TITLE
Merge "charles_dev" - Quality of Life

### PR DESCRIPTION
**Pull request by Charlito33**
Quality of Life

**Changes :**
* Refactored (a lot of) code.
* Added brand name when booting the device.
* Added better error handling.
* Added better log system.
* Added system panic message.
* Added hardware checks.
* Added backtrace (Thanks to @b5i).
* Added battery charging status detection.
* Added device mode management.
* Added enhanced physical input handling.
* Added charging popup (launcher only).
* Added battery level requirement to boot device.
* Added PlatformIO caching (Makes GitHub Actions compilation times 6 times faster).
* Changed battery level estimation.
* Changed battery default value for non-ESP platforms.
* Fixed GUI Image to support scaling.

**Tested on :**
* Paxo v5.1

### CODE REVIEW

**Comment by Charlito33** [comment]
J'ai pas la foi de corriger les merges conflicts.

**Comment by b5i** [comment]
> J'ai pas la foi de corriger les merges conflicts.

Tu veux que je le fasse?

**Comment by Charlito33** [comment]
Vas-y je me motive je vais le faire

**Review by paxo-rch — APPROVED** [review]
Pour moi c'est bon

**Comment by paxo-rch** [comment]
C'est ok pour vous si on merge maintenant?

**Review by b5i — APPROVED** [review]

**Pull request merged**
